dryer:
  duration: "00:15:00"
washing_machine:
  duration: "00:15:00"
stairs_light_timer:
  name: stairs_light_timer
  duration: "00:02:00"
attic_light_timer:
  name: attic_light_timer
  duration: "00:15:00"
basement_light_timer:
  name: basement_light_timer
  duration: "00:05:00"
garage_light_timer:
  name: garage_light_timer
  duration: "00:03:00"
entry_light_timer:
  name: entry_light_timer
  duration: "00:02:00"
mudroom_light_timer:
  name: mudroom_light_timer
  duration: "00:02:00"
kitchen_light_timer:
  name: kitchen_light_timer
  duration: "00:05:00"
dining_room_light_timer:
  name: dining_room_light_timer
  duration: "00:05:00"
living_room_light_timer:
  name: living_room_light_timer
  duration: "00:15:00"
office_light_timer:
  name: office_light_timer
  duration: "00:15:00"
upstairs_hallway_light_timer:
  name: upstairs_hallway_light_timer
  duration: "00:02:00"
bedroom_light_timer:
  name: bedroom_light_timer
  duration: "00:15:00"
bathroom_light_timer:
  name: bathroom_light_timer
  duration: "00:10:00"
downstairs_bathroom_light_timer:
  name: downstairs_bathroom_light_timer
  duration: "00:10:00"
guest_bathroom_light_timer:
  name: guest_bathroom_light_timer
  duration: "00:15:00"
sarah_office_light_timer:
  name: sarah_office_light_timer
  duration: "01:00:00"
closet_room_light_timer:
  name: closet_light_timer
  duration: "00:02:00"
stairs_light_toggle_timer:
  name: stairs_light_toggle_timer
  duration: "00:01:30"
attic_light_toggle_timer:
  name: attic_light_toggle_timer
  duration: "00:01:30"
basement_light_toggle_timer:
  name: basement_light_toggle_timer
  duration: "00:01:30"
garage_light_toggle_timer:
  name: garage_light_toggle_timer
  duration: "00:01:30"
entry_light_toggle_timer:
  name: entry_light_toggle_timer
  duration: "00:01:30"
mudroom_light_toggle_timer:
  name: mudroom_light_toggle_timer
  duration: "00:01:30"
kitchen_light_toggle_timer:
  name: kitchen_light_toggle_timer
  duration: "00:01:30"
dining_room_light_toggle_timer:
  name: dining_room_light_toggle_timer
  duration: "00:01:30"
living_room_light_toggle_timer:
  name: living_room_light_toggle_timer
  duration: "00:01:30"
office_light_toggle_timer:
  name: office_light_toggle_timer
  duration: "00:01:30"
upstairs_hallway_light_toggle_timer:
  name: upstairs_hallway_light_toggle_timer
  duration: "00:01:30"
bedroom_light_toggle_timer:
  name: bedroom_light_toggle_timer
  duration: "00:01:30"
bathroom_light_toggle_timer:
  name: bathroom_light_toggle_timer
  duration: "00:01:30"
downstairs_bathroom_light_toggle_timer:
  name: downstairs_bathroom_light_toggle_timer
  duration: "00:01:30"
guest_bathroom_light_toggle_timer:
  name: guest_bathroom_light_toggle_timer
  duration: "00:01:30"
sarah_office_light_toggle_timer:
  name: sarah_office_light_toggle_timer
  duration: "00:01:30"
closet_room_light_toggle_timer:
  name: closet_light_toggle_timer
  duration: "00:01:30"
