advanced:
  log_directory: data/log
  log_output:
    - file
devices:
  '0x00158d000282af4b':
    friendly_name: mudroom_outlet_0
  '0x00158d000282d11a':
    friendly_name: kitchen_outlet_0
  '0x00158d000282d198':
    friendly_name: bedroom_outlet_0
  '0x00158d000282d46b':
    friendly_name: game_room_outlet_0
  '0x00158d000282d58e':
    friendly_name: living_room_outlet_0
  '0x00158d000282d8aa':
    friendly_name: sarah_office_outlet_0
  '0x00158d00067c3206':
    friendly_name: mudroom_motion_sensor_1
  '0x00158d00067c321e':
    friendly_name: closet_motion_sensor_0
  '0x00158d0006b27e33':
    friendly_name: living_room_temp_sensor
  '0x00158d0006b85fee':
    friendly_name: game_room_temp_sensor
  '0x00158d0006b8acd2':
    friendly_name: office_temp_sensor
  '0x00158d0006ba9ca1':
    friendly_name: basement_stairs_motion_sensor_0
  '0x00158d0006bcad34':
    friendly_name: laundry_room_temp_sensor
  '0x00158d0006bcd7c2':
    friendly_name: guest_room_temp_sensor
  '0x00158d0006bcd918':
    friendly_name: upstairs_hallway_temp_sensor
  '0x00158d0006bd318f':
    friendly_name: bathroom_temp_sensor_0
  '0x00158d0006bde37c':
    friendly_name: cat_room_temp_sensor
  '0x00158d0006bde561':
    friendly_name: attic_temp_sensor
  '0x00158d0006c38f8f':
    friendly_name: entry_motion_sensor_0
  '0x00158d0006c3a0b8':
    friendly_name: mudroom_motion_sensor_0
  '0x00158d0006c3b23f':
    friendly_name: bedroom_motion_sensor_0
  '0x00158d0006c41ec8':
    friendly_name: living_room_motion_sensor_0
  '0x00158d0006c4228c':
    friendly_name: laundry_room_motion_sensor_0
  '0x00158d0006c42640':
    friendly_name: back_stairs_motion_sensor_0
  '0x00158d0006c481f8':
    friendly_name: sarah_office_temp_sensor
  '0x00158d0006c52d72':
    friendly_name: kitchen_motion_sensor_0
  '0x00158d0006c52db1':
    friendly_name: office_motion_sensor_0
  '0x00158d0006c52f69':
    friendly_name: garage_motion_sensor_0
  '0x00158d0006c5f391':
    friendly_name: bedroom_temp_sensor
  '0x00158d0006d0c0a6':
    friendly_name: dining_room_motion_sensor_0
  '0x00158d0006d0c111':
    friendly_name: game_room_motion_sensor_0
  '0x00158d0006d0c1a4':
    friendly_name: upstairs_hallway_motion_sensor_0
  '0x00158d0006d64d72':
    friendly_name: pantry_door_sensor
  '0x00158d0006e967a8':
    friendly_name: front_door_sensor
  '0x00158d0006e9872e':
    friendly_name: laundry_room_water_leak_sensor_0
  '0x00158d0006ea6727':
    friendly_name: back_door_sensor
  '0x00158d0006f155d1':
    friendly_name: workshop_water_leak_sensor_0
  '0x00158d0006f6f6bd':
    friendly_name: side_door_sensor
  '0x00158d0006f8fc4d':
    friendly_name: laundry_room_water_leak_sensor_1
  '0x00158d000700762e':
    friendly_name: mudroom_closet_door_sensor
  '0x5c0272fffeb13afc':
    friendly_name: mudroom_light_0
  '0x5c0272fffeb141f5':
    friendly_name: living_room_flood_7
  '0x5c0272fffeb175a3':
    friendly_name: pantry_light_0
  '0x5c0272fffeb3516b':
    friendly_name: mudroom_light_1
  '0x5c0272fffeb35387':
    friendly_name: mudroom_light_6
  '0x5c0272fffeb356c0':
    friendly_name: upstairs_hallway_light_1
  '0x5c0272fffeb4a514':
    friendly_name: living_room_flood_6
  '0x5c0272fffeb54a73':
    friendly_name: mudroom_light_2
  '0x5c0272fffeb7b88d':
    friendly_name: mudroom_light_3
  '0x5c0272fffeb7c504':
    friendly_name: mudroom_light_4
  '0x5c0272fffeb7da11':
    friendly_name: upstairs_hallway_light_0
  '0x5c0272fffeb82ca2':
    friendly_name: mudroom_light_5
  '0x680ae2fffe844c75':
    friendly_name: bedroom_lights_button
  '0x804b50fffefa985c':
    friendly_name: test_controller
  '0x804b50fffefc65aa':
    friendly_name: living_room_outlet_1
  '0x84fd27fffe05e173':
    friendly_name: office_outlet_0
  '0xb0ce1814001181ff':
    friendly_name: front_entrance_light_0
  '0xb0ce1814001194a1':
    friendly_name: mudroom_closet_light_0
  '0xb0ce181400119512':
    friendly_name: closet_light_0
  '0xb0ce18140011c6ae':
    friendly_name: workshop_light_0
  '0xb0ce18140011e0a7':
    friendly_name: garage_light_0
  '0xb0ce18140011e558':
    friendly_name: basement_stairs_light_0
  '0xb0ce18140012079c':
    friendly_name: laundry_room_light_0
  '0xb0ce181400169fe7':
    friendly_name: bedroom_light_2
  '0xb0ce18140016a0bb':
    friendly_name: bedroom_light_1
  '0xb0ce18140016a94b':
    friendly_name: bedroom_light_0
  '0xb0ce181403010013':
    friendly_name: workshop_light_1
  '0xb0ce181403013c93':
    friendly_name: laundry_room_light_1
  '0xb0ce18140301ba8d':
    friendly_name: laundry_room_light_2
  '0xb0ce1814030991e6':
    friendly_name: game_room_light_5
  '0xb0ce181403099bf3':
    friendly_name: game_room_light_3
  '0xb0ce18140309cb4c':
    friendly_name: game_room_light_1
  '0xb0ce1814030a38c5':
    friendly_name: office_flood_3
  '0xb0ce1814030a6cef':
    friendly_name: kitchen_flood_3
  '0xb0ce1814030a75a4':
    friendly_name: dining_room_flood_0
  '0xb0ce1814030a98d9':
    friendly_name: living_room_flood_1
  '0xb0ce1814030b9cd6':
    friendly_name: downstairs_bathroom_light_0
  '0xb0ce1814030e2f5a':
    friendly_name: guest_bathroom_light_1
  '0xb0ce1814030e78ee':
    friendly_name: game_room_light_7
  '0xb0ce1814030ec1e9':
    friendly_name: game_room_light_6
  '0xb0ce1814030f03f6':
    friendly_name: guest_bathroom_light_0
  '0xb0ce1814030f4039':
    friendly_name: basement_stairs_light_1
  '0xb0ce181403186adc':
    friendly_name: dining_room_flood_1
  '0xb0ce181403187836':
    friendly_name: office_flood_2
  '0xb0ce1814031878ec':
    friendly_name: living_room_flood_2
  '0xb0ce1814031887b8':
    friendly_name: kitchen_flood_1
  '0xb0ce181403189a0c':
    friendly_name: living_room_flood_0
  '0xb0ce18140318a951':
    friendly_name: kitchen_flood_0
  '0xb0ce18140318b1d3':
    friendly_name: office_flood_0
  '0xb0ce18140318b443':
    friendly_name: office_flood_1
  '0xb0ce1814032d4f54':
    friendly_name: dining_room_flood_2
  '0xb0ce1814032d6d38':
    friendly_name: kitchen_flood_2
  '0xb0ce1814032d7047':
    friendly_name: dining_room_flood_3
  '0xb0ce1814032d7273':
    friendly_name: living_room_flood_3
  '0xb0ce1814032d8315':
    friendly_name: living_room_flood_4
  '0xb0ce1814032d980f':
    friendly_name: game_room_light_2
  '0xb0ce1814032dcfa4':
    friendly_name: dining_room_flood_4
  '0xb0ce1814032de418':
    friendly_name: living_room_flood_5
  '0xb0ce1814032dfe73':
    friendly_name: game_room_light_0
  '0xb0ce1814032e00af':
    friendly_name: game_room_light_4
  '0xbc33acfffe584b29':
    friendly_name: office_blinds_1
  '0xbc33acfffe76c97d':
    friendly_name: office_blinds_0
  '0xec1bbdfffeaf8516':
    friendly_name: office_button_0
  '0x680ae2fffe25e066':
    friendly_name: test_shortcut_button
  '0x00158d0006d51f75':
    friendly_name: game_room_vibration_sensor_0
  '0x00158d00067c52b1':
    friendly_name: bathroom_motion_sensor_0
  '0x00158d00067c092e':
    friendly_name: test_motion_sensor
  '0xb0ce181403011cb5':
    friendly_name: test_light
  '0xb0ce1814001c79e9':
    friendly_name: bathroom_light_0
  '0xb0ce1814001c78e6':
    friendly_name: bathroom_light_1
  '0xb0ce1814030dc6f7':
    friendly_name: entry_light_0
  '0x00158d0002a9a417':
    friendly_name: '0x00158d0002a9a417'
  '0x00158d0002a70df0':
    friendly_name: '0x00158d0002a70df0'
frontend:
  auth_token: "REDACTED"
  host: 0.0.0.0
  port: 8080
groups:
  '1':
    devices:
      - office_flood_3
      - office_flood_2
      - office_flood_0
      - office_flood_1
    friendly_name: office_lights
  '2':
    devices:
      - basement_stairs_light_0
      - basement_stairs_light_1
      - laundry_room_light_0
      - laundry_room_light_1
      - laundry_room_light_2
      - game_room_light_5
      - game_room_light_3
      - game_room_light_1
      - game_room_light_7
      - game_room_light_6
      - game_room_light_2
      - game_room_light_0
      - game_room_light_4
      - workshop_light_0
      - workshop_light_1
    friendly_name: basement_lights
  '3':
    devices:
      - bedroom_light_2
      - bedroom_light_1
      - bedroom_light_0
    friendly_name: bedroom_lights
  '4':
    devices:
      - kitchen_flood_3
      - kitchen_flood_1
      - kitchen_flood_0
      - kitchen_flood_2
    friendly_name: kitchen_lights
  '5':
    devices:
      - upstairs_hallway_light_1
      - upstairs_hallway_light_0
    friendly_name: upstairs_hallway_lights
  '6':
    devices:
      - dining_room_flood_0
      - dining_room_flood_1
      - dining_room_flood_2
      - dining_room_flood_3
      - dining_room_flood_4
    friendly_name: dining_room_lights
  '7':
    devices:
      - basement_stairs_light_0
      - basement_stairs_light_1
    friendly_name: basement_stairs_lights
  '8':
    devices:
      - laundry_room_light_0
      - laundry_room_light_1
      - laundry_room_light_2
    friendly_name: laundry_room_lights
  '9':
    devices:
      - workshop_light_0
      - workshop_light_1
    friendly_name: workshop_lights
  '10':
    devices:
      - garage_light_0
    friendly_name: garage_lights
  '11':
    devices:
      - pantry_light_0
    friendly_name: pantry_lights
  '12':
    devices:
      - mudroom_closet_light_0
    friendly_name: mudroom_closet_lights
  '13':
    devices:
      - garage_light_0
      - mudroom_light_0
      - mudroom_light_1
      - mudroom_light_6
      - mudroom_light_2
      - mudroom_light_3
      - mudroom_light_4
      - mudroom_light_5
      - kitchen_flood_3
      - kitchen_flood_1
      - kitchen_flood_0
      - kitchen_flood_2
      - dining_room_flood_0
      - dining_room_flood_1
      - dining_room_flood_2
      - dining_room_flood_3
      - dining_room_flood_4
      - living_room_flood_7
      - living_room_flood_6
      - living_room_flood_1
      - living_room_flood_2
      - living_room_flood_0
      - living_room_flood_3
      - living_room_flood_4
      - living_room_flood_5
      - office_flood_3
      - office_flood_2
      - office_flood_0
      - office_flood_1
      - pantry_light_0
      - mudroom_closet_light_0
    friendly_name: downstairs_lights
  '14':
    devices:
      - upstairs_hallway_light_1
      - upstairs_hallway_light_0
      - bedroom_light_2
      - bedroom_light_1
      - bedroom_light_0
      - downstairs_bathroom_light_0
      - guest_bathroom_light_1
      - guest_bathroom_light_0
      - closet_light_0
    friendly_name: upstairs_lights
  '15':
    devices:
      - front_entrance_light_0
    friendly_name: front_entrance_lights
  '16':
    devices:
      - front_entrance_light_0
    friendly_name: outside_lights
  '17':
    devices:
      - closet_light_0
    friendly_name: closet_lights
  '18':
    devices:
      - mudroom_light_0
      - mudroom_light_1
      - mudroom_light_6
      - mudroom_light_2
      - mudroom_light_3
      - mudroom_light_4
      - mudroom_light_5
    friendly_name: mudroom_lights
  '19':
    devices:
      - living_room_flood_7
      - living_room_flood_6
      - living_room_flood_1
      - living_room_flood_2
      - living_room_flood_0
      - living_room_flood_3
      - living_room_flood_4
      - living_room_flood_5
    friendly_name: living_room_lights
  '20':
    devices:
      - bathroom_light_0
      - bathroom_light_1
    friendly_name: bathroom_lights
  '21':
    devices:
      - game_room_light_5
      - game_room_light_3
      - game_room_light_1
      - game_room_light_7
      - game_room_light_6
      - game_room_light_2
      - game_room_light_0
      - game_room_light_4
    friendly_name: game_room_lights
  '22':
    devices:
      - guest_bathroom_light_1
      - guest_bathroom_light_0
    friendly_name: guest_bathroom_lights
homeassistant: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost
permit_join: true
serial:
  port: /dev/ttyACM0
