random_night_lights:
  name: bedtime
  icon: mdi:car
  initial: 'off'
downstairs_bathroom_door_closed:
  name: Downstairs bathroom door closed
  icon: mdi:home-export-outline
washing_machine_in_progress:
  name: washing machine in progress
  icon: mdi:home-export-outline
  initial: 'off'
washing_machine_done:
  name: washing machine done
  icon: mdi:home-export-outline
  initial: 'off'
dryer_in_progress:
  name: dryer in progress
  icon: mdi:home-export-outline
  initial: 'off'
dryer_done:
  name: dryer done
  icon: mdi:home-export-outline
  initial: 'off'
living_room_override:
  name: living_room_override
  icon: mdi:home-export-outline
  initial: 'off'
stairs_light_override:
  name: stairs light override
  icon: mdi:home-export-outline
  initial: 'off'
back_stairs_light_override:
  name: back_stairs light override
  icon: mdi:home-export-outline
  initial: 'off'
attic_light_override:
  name: attic light override
  icon: mdi:home-export-outline
  initial: 'off'
basement_light_override:
  name: basement light override
  icon: mdi:home-export-outline
  initial: 'off'
laundry_room_light_override:
  name: laundry_room light override
  icon: mdi:home-export-outline
  initial: 'off'
game_room_light_override:
  name: game_room light override
  icon: mdi:home-export-outline
  initial: 'off'
workshop_light_override:
  name: workshop light override
  icon: mdi:home-export-outline
  initial: 'off'
garage_light_override:
  name: garage light override
  icon: mdi:home-export-outline
  initial: 'off'
entry_light_override:
  name: entry light override
  icon: mdi:home-export-outline
  initial: 'off'
mudroom_light_override:
  name: mudroom light override
  icon: mdi:home-export-outline
  initial: 'off'
kitchen_light_override:
  name: kitchen light override
  icon: mdi:home-export-outline
  initial: 'off'
dining_room_light_override:
  name: dining_room light override
  icon: mdi:home-export-outline
  initial: 'off'
living_room_light_override:
  name: living_room light override
  icon: mdi:home-export-outline
  initial: 'off'
office_light_override:
  name: office light override
  icon: mdi:home-export-outline
  initial: 'off'
pantry_light_override:
  name: pantry light override
  icon: mdi:home-export-outline
  initial: 'off'
mudroom_closet_light_override:
  name: mudroom_closet light override
  icon: mdi:home-export-outline
  initial: 'off'
upstairs_hallway_light_override:
  name: upstairs_hallway light override
  icon: mdi:home-export-outline
  initial: 'off'
bedroom_light_override:
  name: bedroom light override
  icon: mdi:home-export-outline
  initial: 'off'
bathroom_light_override:
  name: bathroom light override
  icon: mdi:home-export-outline
  initial: 'off'
downstairs_bathroom_light_override:
  name: bathroom light override
  icon: mdi:home-export-outline
  initial: 'off'
guest_bathroom_light_override:
  name: guest_bathroom light override
  icon: mdi:home-export-outline
  initial: 'off'
sarah_office_light_override:
  name: sarah_office light override
  icon: mdi:home-export-outline
  initial: 'off'
cat_room_light_override:
  name: cat_room light override
  icon: mdi:home-export-outline
  initial: 'off'
guest_room_light_override:
  name: guest_room light override
  icon: mdi:home-export-outline
  initial: 'off'
closet_room_light_override:
  name: closet light override
  icon: mdi:home-export-outline
  initial: 'off'
stairs_light_is_running:
  name: stairs light is running
  icon: mdi:home-export-outline
  initial: 'off'
back_stairs_light_is_running:
  name: back_stairs light is running
  icon: mdi:home-export-outline
  initial: 'off'
attic_light_is_running:
  name: attic light is running
  icon: mdi:home-export-outline
  initial: 'off'
basement_light_is_running:
  name: basement light is running
  icon: mdi:home-export-outline
  initial: 'off'
laundry_room_light_is_running:
  name: laundry_room light is running
  icon: mdi:home-export-outline
  initial: 'off'
game_room_light_is_running:
  name: game_room light is running
  icon: mdi:home-export-outline
  initial: 'off'
workshop_light_is_running:
  name: workshop light is running
  icon: mdi:home-export-outline
  initial: 'off'
garage_light_is_running:
  name: garage light is running
  icon: mdi:home-export-outline
  initial: 'off'
entry_light_is_running:
  name: entry light is running
  icon: mdi:home-export-outline
  initial: 'off'
mudroom_light_is_running:
  name: mudroom light is running
  icon: mdi:home-export-outline
  initial: 'off'
kitchen_light_is_running:
  name: kitchen light is running
  icon: mdi:home-export-outline
  initial: 'off'
dining_room_light_is_running:
  name: dining_room light is running
  icon: mdi:home-export-outline
  initial: 'off'
living_room_light_is_running:
  name: living_room light is running
  icon: mdi:home-export-outline
  initial: 'off'
office_light_is_running:
  name: office light is running
  icon: mdi:home-export-outline
  initial: 'off'
pantry_light_is_running:
  name: pantry light is running
  icon: mdi:home-export-outline
  initial: 'off'
mudroom_closet_light_is_running:
  name: mudroom_closet light is running
  icon: mdi:home-export-outline
  initial: 'off'
upstairs_hallway_light_is_running:
  name: upstairs_hallway light is running
  icon: mdi:home-export-outline
  initial: 'off'
bedroom_light_is_running:
  name: bedroom light is running
  icon: mdi:home-export-outline
  initial: 'off'
bathroom_light_is_running:
  name: bathroom light is running
  icon: mdi:home-export-outline
  initial: 'off'
guest_bathroom_light_is_running:
  name: guest_bathroom light is running
  icon: mdi:home-export-outline
  initial: 'off'
sarah_office_light_is_running:
  name: sarah_office light is running
  icon: mdi:home-export-outline
  initial: 'off'
cat_room_light_is_running:
  name: cat_room light is running
  icon: mdi:home-export-outline
  initial: 'off'
guest_room_light_is_running:
  name: guest_room light is running
  icon: mdi:home-export-outline
  initial: 'off'
closet_room_light_is_running:
  name: closet light is running
  icon: mdi:home-export-outline
  initial: 'off'
always_false:
  name: always false
  icon: mdi:home-export-outline
  initial: 'off'
living_room_toggle_override:
  name: living_room_override
  icon: mdi:home-export-outline
  initial: 'off'
stairs_light_toggle_override:
  name: stairs light override
  icon: mdi:home-export-outline
  initial: 'off'
back_stairs_light_toggle_override:
  name: back_stairs light override
  icon: mdi:home-export-outline
  initial: 'off'
attic_light_toggle_override:
  name: attic light override
  icon: mdi:home-export-outline
  initial: 'off'
basement_light_toggle_override:
  name: basement light override
  icon: mdi:home-export-outline
  initial: 'off'
laundry_room_light_toggle_override:
  name: laundry_room light override
  icon: mdi:home-export-outline
  initial: 'off'
game_room_light_toggle_override:
  name: game_room light override
  icon: mdi:home-export-outline
  initial: 'off'
workshop_light_toggle_override:
  name: workshop light override
  icon: mdi:home-export-outline
  initial: 'off'
garage_light_toggle_override:
  name: garage light override
  icon: mdi:home-export-outline
  initial: 'off'
entry_light_toggle_override:
  name: entry light override
  icon: mdi:home-export-outline
  initial: 'off'
mudroom_light_toggle_override:
  name: mudroom light override
  icon: mdi:home-export-outline
  initial: 'off'
kitchen_light_toggle_override:
  name: kitchen light override
  icon: mdi:home-export-outline
  initial: 'off'
dining_room_light_toggle_override:
  name: dining_room light override
  icon: mdi:home-export-outline
  initial: 'off'
living_room_light_toggle_override:
  name: living_room light override
  icon: mdi:home-export-outline
  initial: 'off'
office_light_toggle_override:
  name: office light override
  icon: mdi:home-export-outline
  initial: 'off'
pantry_light_toggle_override:
  name: pantry light override
  icon: mdi:home-export-outline
  initial: 'off'
mudroom_closet_light_toggle_override:
  name: mudroom_closet light override
  icon: mdi:home-export-outline
  initial: 'off'
upstairs_hallway_light_toggle_override:
  name: upstairs_hallway light override
  icon: mdi:home-export-outline
  initial: 'off'
bedroom_light_toggle_override:
  name: bedroom light override
  icon: mdi:home-export-outline
  initial: 'off'
bathroom_light_toggle_override:
  name: bathroom light override
  icon: mdi:home-export-outline
  initial: 'off'
guest_bathroom_light_toggle_override:
  name: guest_bathroom light override
  icon: mdi:home-export-outline
  initial: 'off'
sarah_office_light_toggle_override:
  name: sarah_office light override
  icon: mdi:home-export-outline
  initial: 'off'
cat_room_light_toggle_override:
  name: cat_room light override
  icon: mdi:home-export-outline
  initial: 'off'
guest_room_light_toggle_override:
  name: guest_room light override
  icon: mdi:home-export-outline
  initial: 'off'
closet_room_light_toggle_override:
  name: closet light override
  icon: mdi:home-export-outline
  initial: 'off'
living_room_occupancy:
  name: living_room is occupied
  icon: mdi:home-export-outline
  initial: 'off'