title: Home
views:
- cards:
  - entities:
    - light.basement_lights
    - light.basement_stairs_lights
    - light.basement_stairs_light_0
    - light.basement_stairs_light_1
    - light.laundry_room_lights
    - light.laundry_room_light_0
    - light.laundry_room_light_1
    - light.laundry_room_light_2
    - light.game_room_lights
    - light.game_room_light_5
    - light.game_room_light_3
    - light.game_room_light_1
    - light.game_room_light_7
    - light.game_room_light_6
    - light.game_room_light_2
    - light.game_room_light_0
    - light.game_room_light_4
    - light.workshop_lights
    - light.workshop_light_0
    - light.workshop_light_1
    title: basement
    type: entities
  - entities:
    - light.downstairs_lights
    - light.garage_lights
    - light.garage_light_0
    - light.mudroom_lights
    - light.mudroom_light_0
    - light.mudroom_light_1
    - light.mudroom_light_6
    - light.mudroom_light_2
    - light.mudroom_light_3
    - light.mudroom_light_4
    - light.mudroom_light_5
    - light.kitchen_lights
    - light.kitchen_flood_3
    - light.kitchen_flood_1
    - light.kitchen_flood_0
    - light.kitchen_flood_2
    - light.dining_room_lights
    - light.dining_room_flood_0
    - light.dining_room_flood_1
    - light.dining_room_flood_2
    - light.dining_room_flood_3
    - light.dining_room_flood_4
    - light.living_room_lights
    - light.living_room_flood_7
    - light.living_room_flood_6
    - light.living_room_flood_1
    - light.living_room_flood_2
    - light.living_room_flood_0
    - light.living_room_flood_3
    - light.living_room_flood_4
    - light.living_room_flood_5
    - light.office_lights
    - light.office_flood_3
    - light.office_flood_2
    - light.office_flood_0
    - light.office_flood_1
    - cover.office_blinds_1
    - cover.office_blinds_0
    - light.pantry_lights
    - light.pantry_light_0
    - light.mudroom_closet_lights
    - light.mudroom_closet_light_0
    title: downstairs
    type: entities
  - entities:
    - light.upstairs_lights
    - light.upstairs_hallway_lights
    - light.upstairs_hallway_light_1
    - light.upstairs_hallway_light_0
    - light.bedroom_lights
    - light.bedroom_light_2
    - light.bedroom_light_1
    - light.bedroom_light_0
    - light.bathroom_lights
    - light.downstairs_bathroom_light_0
    - light.guest_bathroom_lights
    - light.guest_bathroom_light_1
    - light.guest_bathroom_light_0
    - light.closet_lights
    - light.closet_light_0
    title: upstairs
    type: entities
  - entities:
    - light.outside_lights
    - light.front_entrance_lights
    - light.front_entrance_light_0
    title: outside
    type: entities
  path: default_view
  title: Home
