name: Validate YAML

on:
  push:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate YAML
        run: |
          for file in $(find . -name "*.yml" -o -name "*.yaml");
          do
            echo "Validating $file"
            yamllint -d "{extends: relaxed, rules: {line-length: {max: 120}}}" $file
          done